title: 2022 LUNA
email: admin@lunacoding.com
description: >- # this means to ignore newlines until "baseurl:"
  2022년, 지지 않는 달 'LUNA'의 소개 페이지입니다.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
github_username: LUNA-DIMIGO
destination: ./_site

# Build settings
theme: minima
plugins:
  - jekyll-feed
  - jekyll-autoprefixer

config: utf-8

collections:
  members:
  awards:
  items:

navigation:
  - title: LUNA
    url: /luna.html
    icon: fa-moon

  - title: Member
    url: /member.html
    icon: fa-users

  - title: Item
    url: /item.html
    icon: fa-lightbulb

  - title: Award
    url: /award.html
    icon: fa-trophy

  - title: FAQ
    url: /faq.html
    icon: fa-question-circle
google-analytics:
  tracking_id: G-T18S2GPNJD
# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
